---
- name: Install etcd-package
  apt:
    name: [ 'etcd' ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes

# - name: Install etcd-client-package 
#   apt:
#     name: [ 'etcd-client' ]
#     state: present
#     update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
#   become: yes